### ISSUE TITLE
Add unit test 

### ISSUE THREAD

**Issue by friedger** [ABRAHAMEKIO/Smart-Wallet#4]
Add unit test for unhappy stx transfer

**Comment by ABRAHAMEKIO** [comment]
added unit tests for unhappy stx transfer and other transfer functions @friedger 
[https://github.com/ABRAHAMEKIO/Smart-Wallet/commit/cee7c840fe0a510bcc61ba07f274506526d7cf3c](url)

**Comment by friedger** [comment]
Structure is now available
